// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teowcywyqjtaorzgquxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlb3djeXd5cWp0YW9yemdxdXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzM5MDYsImV4cCI6MjA2MDA0OTkwNn0._qs5EDulsb6Oli0q1s7v164iZiWr5R8WLfEvB2MdyZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);